# Basic statistics

In [1]:
import pandas as pd

1.	Load the patient dataset and show summary with info().

In [3]:
df=pd.read_csv('Patient_Data.csv')

In [29]:
df1=pd.read_csv('Billing_Data.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].

In [51]:
billing_info = ['PatientID', 'Department', 'Doctor', 'BillAmount']
df[billing_info]

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].

In [9]:
df.drop(columns=['ReceptionistID', 'CheckInTime'])

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

4.	Use groupby to find total bill amount per department.

In [11]:
df.groupby('Department')['BillAmount'].sum().reset_index()

    Department  BillAmount
0   Cardiology     16200.0
1  Dermatology         0.0
2    Neurology         0.0
3  Orthopedics      7500.0

5.	Remove duplicate patient records based on PatientID.

In [14]:
df[df.duplicated()]

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [23]:
drop_df=df.drop_duplicates()
drop_df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

6.	Fill missing BillAmount values with the mean bill amount.

In [16]:
mean_bill=df['BillAmount'].mean()
mean_bill

np.float64(5925.0)

In [27]:
filled_df=drop_df.fillna({'BillAmount': mean_bill})
filled_df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,5925.0,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,5925.0,2,2023-01-14 08:45

7.	Merge the billing dataset with patient dataset on PatientID.

In [37]:
merged_df = pd.merge(filled_df, df1, on='PatientID')
merged_df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,2000,3000
1,102,Bob,Neurology,Dr. John,5925.0,2,2023-01-11 10:30,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00,3000,3200
4,105,Eva,Dermatology,Dr. Rose,5925.0,2,2023-01-14 08:45,1000,4000

8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

In [40]:
new_patients_data = {
    'PatientID': [106, 107],
    'Name': ['Frank', 'Grace'],
    'Department': ['Neurology', 'Orthopedics'],
    'Doctor': ['Dr. John', 'Dr. Lee'],
    'BillAmount': [4200.0, 5100.0],
    'ReceptionistID': [3, 1],
    'CheckInTime': ['2023-01-15 14:00', '2023-01-16 09:15']
}

new_df = pd.DataFrame(new_patients_data)
new_df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,106,Frank,Neurology,Dr. John,4200.0,3,2023-01-15 14:00
1,107,Grace,Orthopedics,Dr. Lee,5100.0,1,2023-01-16 09:15

In [45]:
con_df=pd.concat([filled_df,new_df],ignore_index=True)
con_df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,5925.0,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,5925.0,2,2023-01-14 08:45
5,106,Frank,Neurology,Dr. John,4200.0,3,2023-01-15 14:00
6,107,Grace,Orthopedics,Dr. Lee,5100.0,1,2023-01-16 09:15

9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [48]:
new_billing = pd.DataFrame({
    'DoctorFee': [1500, 1800, 2000, 1500, 1200, 1500, 1800],
    'MedicineCharges': [450, 600, 750, 300, 500, 450, 800]
})

final_df = pd.concat([con_df, new_billing], axis=1)
final_df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,DoctorFee,MedicineCharges
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,1500,450
1,102,Bob,Neurology,Dr. John,5925.0,2,2023-01-11 10:30,1800,600
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00,2000,750
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00,1500,300
4,105,Eva,Dermatology,Dr. Rose,5925.0,2,2023-01-14 08:45,1200,500
5,106,Frank,Neurology,Dr. John,4200.0,3,2023-01-15 14:00,1500,450
6,107,Grace,Orthopedics,Dr. Lee,5100.0,1,2023-01-16 09:15,1800,800