# Python Assignment: Data Structures, Functions, Numpy & Pandas

## Section A: Data Structures & Control Structures

1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [78]:
lst1=[12,4,65,39,78]
lst1

[12, 4, 65, 39, 78]

In [79]:
type(lst1)

list

In [80]:
### append
lst1.append(90)
lst1

[12, 4, 65, 39, 78, 90]

In [81]:
### extend
lst1.extend([20,39,40])

In [82]:
lst1

[12, 4, 65, 39, 78, 90, 20, 39, 40]

In [83]:
### insert
lst1.insert(0,3)
lst1

[3, 12, 4, 65, 39, 78, 90, 20, 39, 40]

In [84]:
### remove
lst1.remove(78)
lst1

[3, 12, 4, 65, 39, 90, 20, 39, 40]

In [85]:
### pop
lst1.pop(3)
lst1

[3, 12, 4, 39, 90, 20, 39, 40]

In [86]:
### index
lst1.index(39,4)

6

In [87]:
### count
lst1.count(39)

2

In [88]:
### sort
lst1.sort()
lst1

[3, 4, 12, 20, 39, 39, 40, 90]

In [89]:
### reverse
lst1.reverse()
lst1

[90, 40, 39, 39, 20, 12, 4, 3]

In [90]:
### clear
lst1.clear()
lst1

[]

2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [91]:
student_name=('Karthik','Abhishek','Tharunika')
student_name

('Karthik', 'Abhishek', 'Tharunika')

In [92]:
type(student_name)

tuple

In [93]:
# student_name[2]='Tharu'

* If we try to change the name we will get error.
* In tuple we cant chnage the enteries  because tuples are immutable (unchangeable).

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [94]:
set1={80,250,345,25,142,300,25}

In [95]:
type(set1)

set

In [96]:
set1

{25, 80, 142, 250, 300, 345}

* Set removes the duplicates if present, the output shows only once and keep unique items.
  Here 25 is written twice in the set but in output the 25 is written only once.
* Set shuffles the order and output is printed in ascending order.

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [97]:
dict1={'name':['Karthik','Abhishek','Tharunika'],
       'age':[23,21,13],
       'city':['Bangalore','Mysore','Chintamani']
      }
dict1

{'name': ['Karthik', 'Abhishek', 'Tharunika'],
 'age': [23, 21, 13],
 'city': ['Bangalore', 'Mysore', 'Chintamani']}

In [98]:
type(dict1)

dict

In [99]:
dict1['age'][2]=8
dict1

{'name': ['Karthik', 'Abhishek', 'Tharunika'],
 'age': [23, 21, 8],
 'city': ['Bangalore', 'Mysore', 'Chintamani']}

In [100]:
dict1['email']=['karthikrs@gmail.com','abhishek@gmail.com','tharunika@gmail.com']

In [101]:
dict1

{'name': ['Karthik', 'Abhishek', 'Tharunika'],
 'age': [23, 21, 8],
 'city': ['Bangalore', 'Mysore', 'Chintamani'],
 'email': ['karthikrs@gmail.com', 'abhishek@gmail.com', 'tharunika@gmail.com']}

5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [102]:
age = int(input("Enter your age to check eligibility for voting: "))

if age >= 18:
    print("You are eligible to vote")
else:
    print("You are not eligible to vote yet.")

Enter your age to check eligibility for voting:  23

You are eligible to vote

6.	Given a 'marks' variable, print the grade:
    - 90 and above: 'A'
    - 75–89: 'B'
    - 50–74: 'C'
    - Below 50: 'Fail'

In [103]:
marks = int(input("Enter your marks to get the Grade: "))

if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")

Enter your marks to get the Grade:  68

Grade: C

7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [104]:
num = int(input("Enter a number: "))

if num > 0:
    if num % 2 == 0:
        print(f"The number {num} is positive and even.")
    else:
        print(f"The number {num} is positive but odd.")

elif num == 0:
    print("The number is zero.")

else:
    print(f"The number {num} is negative.")

Enter a number:  7

The number 7 is positive but odd.

## Section B: Numpy

8.	Create:
- A scalar using np.array(5)

In [2]:
import numpy as np
scalar=np.array(5)
scalar

array(5)

- A 1D array with values 1 to 5

In [6]:
arr_1D=np.arange(1,6)
arr_1D

array([1, 2, 3, 4, 5])

- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [7]:
arr_2D=np.array([10,20,30,40,50,60]).reshape(2,3)
arr_2D

array([[10, 20, 30],
       [40, 50, 60]])

9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [11]:
rand_arr=np.random.randint(0,100, size=(4,4))
rand_arr

array([[83, 93, 83, 91],
       [29, 74, 10, 27],
       [24, 45, 62, 67],
       [19,  2, 73, 32]], dtype=int32)

10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [18]:
arr_2D=np.array([10,15,20,30,35,40,45,50,55]).reshape(3,3)
arr_2D

array([[10, 15, 20],
       [30, 35, 40],
       [45, 50, 55]])

In [21]:
import pandas as pd
data=pd.DataFrame(arr_2D, columns=['A', 'B','C'])
data

    A   B   C
0  10  15  20
1  30  35  40
2  45  50  55

## Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [64]:
df={'Name': ['Aravind', 'Ananya', 'Vinay', 'Divya', 'Kabir', 'Isha', 'Arjun', 'Meera', 'Aravind', 'Rohan'],
    'Age': [25, 30, 22, 28, 35, 29, 40, 31, 25, 27],
    'City': ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Pune', 'Chennai', 'Kolkata', 'Ahmedabad', 'Mumbai', 'Jaipur'],
    'Salary': [70000, np.nan, 85000, 95000, 60000, np.nan, 52000, 88000, 70000, 62000]
   }
df

{'Name': ['Aravind',
  'Ananya',
  'Vinay',
  'Divya',
  'Kabir',
  'Isha',
  'Arjun',
  'Meera',
  'Aravind',
  'Rohan'],
 'Age': [25, 30, 22, 28, 35, 29, 40, 31, 25, 27],
 'City': ['Mumbai',
  'Delhi',
  'Bangalore',
  'Hyderabad',
  'Pune',
  'Chennai',
  'Kolkata',
  'Ahmedabad',
  'Mumbai',
  'Jaipur'],
 'Salary': [70000, nan, 85000, 95000, 60000, nan, 52000, 88000, 70000, 62000]}

In [65]:
df=pd.DataFrame(df)

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [67]:
df.describe()

             Age        Salary
count  10.000000      8.000000
mean   29.200000  72750.000000
std     5.245104  15125.664094
min    22.000000  52000.000000
25%    25.500000  61500.000000
50%    28.500000  70000.000000
75%    30.750000  85750.000000
max    40.000000  95000.000000

In [68]:
df[['Name','City']]

      Name       City
0  Aravind     Mumbai
1   Ananya      Delhi
2    Vinay  Bangalore
3    Divya  Hyderabad
4    Kabir       Pune
5     Isha    Chennai
6    Arjun    Kolkata
7    Meera  Ahmedabad
8  Aravind     Mumbai
9    Rohan     Jaipur

In [69]:
df.drop(columns=['City'])

      Name  Age   Salary
0  Aravind   25  70000.0
1   Ananya   30      NaN
2    Vinay   22  85000.0
3    Divya   28  95000.0
4    Kabir   35  60000.0
5     Isha   29      NaN
6    Arjun   40  52000.0
7    Meera   31  88000.0
8  Aravind   25  70000.0
9    Rohan   27  62000.0

In [70]:
df.isnull().sum()

Name      0
Age       0
City      0
Salary    2
dtype: int64

In [71]:
mean_salary=df['Salary'].mean()
mean_salary

np.float64(72750.0)

In [74]:
df.fillna({'Salary': mean_salary}, inplace=True)
df['Salary']

0    70000.0
1    72750.0
2    85000.0
3    95000.0
4    60000.0
5    72750.0
6    52000.0
7    88000.0
8    70000.0
9    62000.0
Name: Salary, dtype: float64

In [75]:
df.duplicated().sum()

np.int64(1)

In [76]:
df[df.duplicated()]

      Name  Age    City   Salary
8  Aravind   25  Mumbai  70000.0

In [77]:
df.drop_duplicates(inplace=True,ignore_index=True)
df

      Name  Age       City   Salary
0  Aravind   25     Mumbai  70000.0
1   Ananya   30      Delhi  72750.0
2    Vinay   22  Bangalore  85000.0
3    Divya   28  Hyderabad  95000.0
4    Kabir   35       Pune  60000.0
5     Isha   29    Chennai  72750.0
6    Arjun   40    Kolkata  52000.0
7    Meera   31  Ahmedabad  88000.0
8    Rohan   27     Jaipur  62000.0